### ISSUE TITLE
How to delete direct message?

### ISSUE THREAD

**Issue by chaoscreater** [sgreben/slack-wipe#1]
Hi there,

I got it working for a team channel, but how can we use this for direct messages? I've tried pasting the direct message ID and it doesn't work. The direct messages have full names, so I tried using -channel="Firstname Lastname" and that didn't work either...

**Comment by sgreben** [comment]
Hey @chaoscreater, sorry about the delay! No idea why I didnt see this issue before..

Now I've addressed this issue (in the `0.3.0` release) - you can use

```sh
slack-wipe -im @someone,@someone.else -messages
``` 

to wipe (or `-redact`) DMs :)
